version: "2"

services:
  idrive:
    build: ./idrive/build/
    image: idrive-docker:latest
    container_name: idrive
    volumes:
      - idrive:/IDriveForLinux/idriveIt
      - /path/to/backup:/source/1:ro
    restart: unless-stopped

volumes:
  idrive:

